function(coredesk_set_target_warnings target_name)
    if(MSVC)
        target_compile_options(${target_name} PRIVATE /W4 /EHsc)
        if(COREDESK_WARNINGS_AS_ERRORS)
            target_compile_options(${target_name} PRIVATE /WX)
        endif()
    else()
        target_compile_options(${target_name} PRIVATE -Wall -Wextra -Wpedantic)
        if(COREDESK_WARNINGS_AS_ERRORS)
            target_compile_options(${target_name} PRIVATE -Werror)
        endif()
    endif()
endfunction()
