function(coredesk_enable_sanitizers target_name)
    if(COREDESK_ENABLE_ASAN AND COREDESK_ENABLE_TSAN)
        message(FATAL_ERROR "COREDESK_ENABLE_ASAN and COREDESK_ENABLE_TSAN cannot both be ON")
    endif()

    if(MSVC)
        if(COREDESK_ENABLE_ASAN)
            target_compile_options(${target_name} PRIVATE /fsanitize=address)
            target_link_options(${target_name} PRIVATE /fsanitize=address)
        elseif(COREDESK_ENABLE_TSAN)
            message(FATAL_ERROR "ThreadSanitizer is not supported by MSVC in this configuration")
        endif()
    else()
        if(COREDESK_ENABLE_ASAN)
            target_compile_options(${target_name} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
            target_link_options(${target_name} PRIVATE -fsanitize=address)
        elseif(COREDESK_ENABLE_TSAN)
            target_compile_options(${target_name} PRIVATE -fsanitize=thread -fno-omit-frame-pointer)
            target_link_options(${target_name} PRIVATE -fsanitize=thread)
        endif()
    endif()
endfunction()
